version: '3.8'

services:
  redis:
    image: redis:latest # Aquí especificas la imagen de Redis
    container_name: redis-server
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ] # Configurar la contraseña de Redis
    ports:
      - "6379:6379" # Expone Redis en el puerto 6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network

  backend:
    build: ./server # Ruta donde está el Dockerfile del backend
    container_name: backend
    ports:
      - "3001:3001" # Expone el backend en el puerto 3001
    environment:
      - REDIS_URL=redis # Dirección del servicio Redis
      - REDIS_PASSWORD=${REDIS_PASSWORD} # Contraseña de Redis
    depends_on:
      - redis # Hace que Redis se levante antes que el backend
    networks:
      - app-network
    volumes:
      - ./server:/app/backend # Ruta personalizada
    command: [ "npm", "run", "dev" ]

  frontend:
    build: ./client # Ruta donde está el Dockerfile del frontend
    container_name: frontend
    ports:
      - "5173:5173" # Expone el frontend en el puerto 5173 (si usas Vite)
    depends_on:
      - backend # Hace que el backend se levante antes que el frontend
    networks:
      - app-network
    volumes:
      - ./client:/app/frontend # Ruta personalizada
    image: node:20
    command: [ "npm", "run", "dev" ]
networks:
  app-network:
    driver: bridge
