version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network
    volumes:
      - redis-data:/data

  backend:
    build: ./server
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./server:/app
      - ./server/src:/app/src
    command: [ "npm", "run", "serve" ]

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./client:/app
      - ./client/src:/app/src
      - ./client/vite.config.ts:/app/vite.config.ts
    image: node:20
    command: [ "npm", "run", "dev" ]
networks:
  app-network:
    driver: bridge

volumes:
  redis-data: {}
